### ISSUE TITLE
下载的真是会员音乐吗？

### ISSUE THREAD

**Issue by SeekingMini** [pyexile/vipMusic#2]
使用qq音乐下载器，下载下来的m4a格式音乐只有几MB，应该不是vip音乐吧？

**Comment by weitw** [comment]
这儿说的vip音乐不是说能下载的音质高，是说部分只能是vip才能听或者下载的音乐。最后下载下来的音乐音质不一定高。

**Comment by SeekingMini** [comment]
好的
